apiVersion: v1
kind: Service
metadata:
  name: svcexcservice
  labels:
    app: excservice
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 8090
  selector:
    app: excservice
    tier: frontend
